version: '3.8'
services:
  app:
    build:
      context: .
    container_name: PBL6-nodejs-app
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
  #   depends_on:
  #     - db
  # db:
  #   container_name: PBL6-postgres
  #   image: postgres
  #   restart: always
  #   ports:
  #     - '5433:5432'
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: movies_database
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data

  # pgadmin:
  #   container_name: PBL6-pgadmin4
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - '5050:80'
  # minio:
  #   image: minio/minio
  #   container_name: PBL6-minio
  #   ports:
  #     - '9000:9000'
  #     - '9001:9001'
  #   volumes:
  #     - ./storage:/data
  #   environment:
  #     MINIO_ROOT_USER: admin
  #     MINIO_ROOT_PASSWORD: admin123
  #   command:
  #     minio server --console-address ":9001" /data
  redis:
    image: redis:alpine
    container_name: PBL6-redis
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data

networks:
  nodejs-exa:
    driver: bridge
volumes:  # Add a volumes section to define named volumes
  data-redis:  # Define the named volume